apiVersion: v2
name: edgewize
description: Backend of edgewize extension.
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere
annotations:
  extensions.kubesphere.io/foo: bar
dependencies:
  - name: frontend
    tags:
      - extension
#  - name: backend
#    tags:
#      - extension