frontend:
  enabled: true
  image:
    repository: hollisy/edgewize
    tag: v1.0.2

backend:
  enabled: true
  certificateAuthority:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUrZ0F3SUJBZ0lVTEdoZGdoVzhXSFFyaVBLbWc2cFFYZkhaam5rd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0V6RVJNQThHQTFVRUF3d0lSV1JuWlZkcGVtVXdIaGNOTWpNd09URTBNRGN5TXpFM1doY05Nek13T1RFeApNRGN5TXpFM1dqQVRNUkV3RHdZRFZRUUREQWhGWkdkbFYybDZaVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBSzlpdGJHQTExWlhqT3lWZWM0TWJXZ3pldjlMdFRNTmgwcXprQ09YelZIdUphWkYKK21tK3g1SklZSFdlZFU3anQ0WGhVa1VJWDlQc2hPYnJnbHE5bXF0RjllbmJoY08rRnc1UHdyYVVycUxuT1hGeAprTXlPQ2t0TVJMcDJOSUNvN1d2NExwT0owSkg1azNrQlVwZEUzZ3R0L2tlUnRrUmtwZ29QTHN2RXA1R005b3ZzCkZBbWNJRkg3UkNGM2VCeFVxQjd2STYyRTI4WDFHeVUwaUtFckhMcW81REoveFFRZ1JnbWpTc2ZDY0JEOWVpRXUKd1RDenFoYnk0SHZ0a3JOSEw4a1QrNHI3ZzZiOTVueGM5K1A1NDVqcktMQkNZOE05U1RiRTZFUElHc1h3M2lHRgpEcGtpMmk3ZWhpaTJ6dnNCZ21ncE1KNXNYa0FHQU9tQ25tZUt4MDhDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFCkZOaEd2MDVGVS9wVTNnOEpwT3J6Y1ZmZXQzcnBNQjhHQTFVZEl3UVlNQmFBRk5oR3YwNUZVL3BVM2c4SnBPcnoKY1ZmZXQzcnBNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRFZJeTFZSApYNG5jYnVFNXhPNVgxS2lvSjdMaUJnd2h3d3BKODBNUWNKSXd3a2NzY2tocjJ0Zml0amlsRTdjakE0UGxUcVNQCk1zMnpEVllYazIycVcvbDZ5RWU5SFFOUkU5U3hKV09TTjdlVTZqUndkYnJwczlJRG9DWXB1OVZZSXZkT2dMeXMKbWJzVHZ6Q0ZKZWE3bkRtQ0Zwak5pNzBKcFVaOGF0N2hqMk4yU1lrMjZmUGZ3anAwZFlrVjZ0d0FXVzg2dmUwcQpLdjNhK2RscWROcjUrUExpRE9kZEIxV25TMCtzL05XL3I2NTh2U0NmZFZSa1ZVdzRpd3FXS0ZhVWt5WXozMWtnCjVNSVQxYis5ZWJmNVcwRGlwNmVqQWYxRFhFS3BZWnR4REl4S0l3bStNNGlZeFArV1hRZHlkUDUvaFRqVnJoSXEKN2crUnV4TDFFZElzTUVvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcjJLMXNZRFhWbGVNN0pWNXpneHRhRE42LzB1MU13MkhTck9RSTVmTlVlNGxwa1g2CmFiN0hra2hnZFo1MVR1TzNoZUZTUlFoZjAreUU1dXVDV3IyYXEwWDE2ZHVGdzc0WERrL0N0cFN1b3VjNWNYR1EKekk0S1MweEV1blkwZ0tqdGEvZ3VrNG5Ra2ZtVGVRRlNsMFRlQzIzK1I1RzJSR1NtQ2c4dXk4U25rWXoyaSt3VQpDWndnVWZ0RUlYZDRIRlNvSHU4anJZVGJ4ZlViSlRTSW9Tc2N1cWprTW4vRkJDQkdDYU5LeDhKd0VQMTZJUzdCCk1MT3FGdkxnZSsyU3MwY3Z5UlA3aXZ1RHB2M21mRnozNC9uam1Pc29zRUpqd3oxSk5zVG9ROGdheGZEZUlZVU8KbVNMYUx0NkdLTGJPK3dHQ2FDa3dubXhlUUFZQTZZS2VaNHJIVHdJREFRQUJBb0lCQUhMMVk1em1rNzh2Z2RxdApHM3JZb0huMWpJQjhVbGdWWFFHMDh4eXhhczV5SjlGMSt1NkhNMjhKNjlnTXRsMndXMkh3MENrWmxSNW00TEl2CjJuQzU2UUNzeWNTd3RGd2FaQ2hvVlh1eHQwcGwvendCc1dTekVjSkxTcDFoejRZcHMvM2FYa1VzeHo1M2RaZVMKSzEybHNWbVNqbUxBK3RTWG1GSHRvOEhDdEFkdFpXZDB1ZmJ6Y1MwNUxZS3I0Wm5hbWwxeVFXUi9zcTBpRk0zVApEb3plb1RySk0wb0NWL3RaQnlVaXNWZmtadFlwZis4LzJQNGFMclB1U1o2b1h2RXVrRi9JSFZvd3FBeFkxMWJnClR0Q1BiTzE4TFd5ZWZBaks4cjB6MVJRSVI4SkV2NEM0d01KNllGdWxUd3F5SFdPcUhPdDZiSWUyQnZ1anVXengKc0c3OXVLRUNnWUVBMmJpMERwTnBuTFordVU3U0tRQXNwTDZDRmx5NVdVbXgyNFF3bmxaeE05RkVTdzNyanNjSApYaGZhbkFLb3JHd0k3MmlueGlHcVVhQmZ6Sm0wRkFtUmZLNHNLVmlzVzhrTUV5RG9sV2JSVUdKK0QzZGNZR1NDCjhVcE9hdkNhRnYySzYyQWZBa0dPL1I1M0NRVG13U2Q0N2NjV0JGU2F0NGtPdmpJanhUbFhONzhDZ1lFQXpqaUkKM1Z6Tk80WWRJaE1UczBFT1ZTYmp5SFlzRFQxL3pZa3d0RVVhK2dsaS9SeURGWi9iY1h6UUZtSWp1dVI4cGkxdgpYN2JQMGZhMjhiNEo4K05QanEzTURKdjFUMGJhL0NPeHRaT0k2QmZ5N0tjYmF2ZW95N0RtbGNpR2JLZGwweEQzCnQ5UnRYZEZjZWtYN3RtRHhPQk5Rd2dUSUNOVkNiVDZ3NVZKZjFIRUNnWUVBajNjdlp0OXFXM0xCNUhmMDhrR0UKS1hiRG45cXY1QTgwbk5McGVweTVjWXkyOU1JU2MzM2c4L2JCL2NXZXdpZGFaKy9OaGppTzA4VGErNlpZekU5Vgp5Qk81VS9GemVmUHIrZnJZYUFKZGNSdkZ0NGxPbk5IK211TDg4MmppRUw0M3VVd1lndE1TVnVhcFI0OHNReUV3CmhYYUhvb2poZm9sWTVxbUJlcWVET2w4Q2dZQThhTGMvRVRaVm4zM2RRM1ZiNTB6SmlQRGxBaWo1WC9DV1J2L3IKYnVydUg5M05nNUtxdlA5TmlXQnpqaUFsV1ZWaVlLRGxpdW5wK2JteHF4ZkRSKzFBUUkwcmpHd1o0d20zSHNXcQpDU1ByeVVneUp1bVROaVZPTmUzMkpwMnFLb2RiZ3ZidDlONXN3eTJ4NjlwR25MTk0xK3VxU2poR3ppSDlXb1g3ClIxd25JUUtCZ0VONDNYYlpUZzQ2MlV6SDlzMHJOaXZNdVFKbXBGa2JuUmcwOFZYQVoxd2FzRlhIeEVmVlRlb1YKMzY4dFVheTNwVUJHclE3MnlYZklpWTU2RmN4cnNGT3VTdUdhTU9QNE1sVzd1M1RIN2pYZHc4bVZpYnNkaWJHeApTbzFZREYyYXkzK0lkeGJmREExSkdsclpXNmJMLytOazJscVRZMWVxMVhQcHUva3V0MkRaCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  chrony:
    image:
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: ""
      repository: kubesphere/chrony-k8s
      tag: v1.0.0
    nodePort: 30729
    replicas: 1
    timezone: Asia/Shanghai
  controller:
    image:
      repository: kubesphere/edgewize-controller-manager
  fileserver:
    image:
      digest: ""
      pullPolicy: IfNotPresent
      registry: ""
      repository: kubesphere/edgewize-fileserver
      tag: v0.1.0
    nodePort: 30276
    replicaCount: 1
  gateway:
    advertiseAddress:
      - 192.168.11.35
    nodePort:
      cloudhub: 30271
      cloudhubHttps: 30272
      otaport: 30274
      tunnelport: 30273
  global:
    apiserver: null
    image:
      repository: kubesphere/edgewize-apiserver
    imagePullSecrets:
      - zpk-deploy-secret
    imageRegistry: harbor.dev.thingsdao.com
    storageClass: local
    tag: v0.7.4
  values:
    cloudcore:
      cloudCore:
        image:
          pullSecrets:
            - name: edge-deploy-secret
          repository: edgewize/cloudcore
          tag: v1.13.1
        service:
          cloudhubHttpsNodePort: 30272
          cloudhubNodePort: 30271
          cloudhubQuicNodePort: 30001
          cloudstreamNodePort: 30003
          tunnelNodePort: 30273
          type: ClusterIP
      defaultImageRegistry: harbor.dev.thingsdao.com/
    edgeOtaServer:
      defaultImageRegistry: harbor.dev.thingsdao.com/
      gateway:
        advertiseAddress:
          - 192.168.11.35
        nodePort:
          chronyPort: 30729
          otaPort: 30274
      image:
        pullPolicy: IfNotPresent
        repository: kubesphere/edge-ota-server
        tag: v0.2.0
      imagePullSecrets:
        - name: edge-deploy-secret
      service:
        port: 80
        type: ClusterIP
    edgewize:
      apiserver:
        image:
          digest: ""
          pullPolicy: IfNotPresent
          registry: ""
          repository: kubesphere/edgewize-apiserver
          tag: ""
      controller:
        image:
          digest: ""
          pullPolicy: IfNotPresent
          registry: ""
          repository: kubesphere/edgewize-controller-manager
          tag: ""
      global:
        imagePullSecrets:
          - edge-deploy-secret
        imageRegistry: harbor.dev.thingsdao.com
        tag: v0.7.4
    fluentOperator:
      defaultImageRegistry: harbor.dev.thingsdao.com/
      fluentbit:
        imagePullSecrets:
          - name: edge-deploy-secret
      fluentd:
        imagePullSecrets:
          - name: edge-deploy-secret
      operator:
        imagePullSecrets:
          - name: edge-deploy-secret
    ksCore:
      defaultImageRegistry: harbor.dev.thingsdao.com/
    kubefed:
      controllermanager:
        defaultImageRegistry: harbor.dev.thingsdao.com/
    vcluster:
      etcd:
        global:
          imagePullSecrets:
            - edge-deploy-secret
          imageRegistry: harbor.dev.thingsdao.com
          storageClass: local
      serviceAccount:
        imagePullSecrets:
          - name: edge-deploy-secret
      storage:
        className: local
        defaultImageRegistry: harbor.dev.thingsdao.com/
        persistence: true
        provisioning: dynamic
    whizardEdgeAgent:
      defaultImageRegistry: harbor.dev.thingsdao.com/
      imagePullSecrets:
        - name: edge-deploy-secret
      prometheus:
        storage:
          className: local
          prometheus_pv_size: 20Gi
      whizard_edge_proxy:
        edge_gateway_address: https://192.168.11.35:30275
  whizardEdgeGateway:
    advertiseAddress:
      - 192.168.11.35
    image:
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: ""
      repository: kubesphere/whizard-edge-gateway
      tag: v0.3.4
    nodePort: 30275
    replicas: 3