apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentripx.name" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  openpitrix.yaml: |
    openpitrix:
      s3:
        endpoint: http://minio.kubesphere-system:9000
        region: us-east-1
        disableSSL: True
        forcePathStyle: True
        accessKeyID: openpitrixminioaccesskey
        secretAccessKey: openpitrixminiosecretkey
        bucket: app-store
        filePath: {{  .Values.opentripx.path   }}
        leaderElectionNamespace: {{ .Release.Namespace }}
        leaderElectionID: {{ default "ks-controller-manager-leader-election" .Values.opentripx.leaderElectionID }}