apiVersion: v1
name: openpitrix
version: 0.1.0
displayName:
  zh: 应用商店
  en: App Store
description:
  zh: 系统自带应用商店
  en: The system comes with its own app store
keywords:
  - Others
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere
dependencies:
  - name: openpitrix
    condition: openpitrix.enabled
icon: ./favicon.svg
