apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: openpitrix
    component: openpitrix-import-job
  name: openpitrix-import-job
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 100
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-import-job
    spec:
      serviceAccountName: {{ include "opentripx.serviceAccountName" . }}
      restartPolicy: OnFailure
      initContainers:
        - name: wait-apiserver
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z {{ include "opentripx.name" . }}-apiserver.{{ .Release.Namespace }}.svc 80; do echo "waiting for apiserver"; sleep 2; done;']
      containers:
        - name: import
          command:
            - import-app
            - import
          image: {{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}
          imagePullPolicy: {{ .Values.job.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/openpitrix
              name: {{ include "opentripx.name" . }}-config
            - mountPath: {{ .Values.opentripx.path | default "/root/charts"}}
              name: {{ include "opentripx.name" .}}-pvc
      volumes:
        - name: {{ include "opentripx.name" . }}-config
          configMap:
            name: {{ include "opentripx.name" . }}-config
        - name: {{ include "opentripx.name" .}}-pvc
          persistentVolumeClaim:
            claimName: {{ include "opentripx.name" .}}-pvc